# wandb 설정
wandb:
    project: "Surround360"
    name: "surround_360_training"

# 모델 설정
model:
    name: "surround"
    pretrain_name: "Salesforce/blip2-opt-2.7b" # HuggingFace 형식으로 저장된 경로
    save_dir: "saved_models/surround_360"
    max_new_tokens: 50 # 최대 생성 토큰 수
    num_query_tokens: 128 # Q-Former의 쿼리 토큰 수 original: 32
    qformer:
        hidden_size: 1024 # 원하는 Q-Former 레이어 수로 변경 original: 768

# 데이터 설정
data:
    dir: "data/quic360"
    train_file: "train.csv"
    valid_file: "valid.csv"
    image_size: [ 224, 224 ]
    max_length: 256
    do_crop: true
    fov: 90 # FOV 설정
    overlap_ratio: 0.5

# deepspeed 설정
deepspeed:
    enabled: false
    config: "config/zero.json"

# 학습 설정
training:
    output_dir: "outputs/surround_360"
    run_name: "surround_360"
    num_epochs: 50
    batch_size:
        train: 64
        eval: 256
    gradient_accumulation_steps: 1 # 효과적인 배치 크기 16
    dataloader_num_workers: 16 # CPU 병렬 처리 추가
    gradient_checkpointing: true # 메모리 최적화

    # 학습률 및 최적화
    learning_rate: 2e-5
    warmup_ratio: 0.1 # warmup 단계 추가
    weight_decay: 0.01

    # 로깅 및 저장 설정
    logging_dir: "logs/blip2_360"
    logging_steps: 4 # 더 자주 로깅
    eval_strategy: "steps" # step 기반으로 변경
    eval_steps: 50 # 500 step마다 평가
    save_strategy: "steps" # step 기반 저장
    save_steps: 50
    save_total_limit: 3 # 최대 3개 체크포인트 유지
    load_best_model_at_end: true
    metric_for_best_model: "eval_loss" # 최상의 모델 기준
    greater_is_better: false

    # 보고 설정
    report_to: "wandb"

    # 추가 최적화
    max_grad_norm: 1.0 # gradient clipping
